name: Build Project

on:
  push:
    branches:
      - main  # 触发工作流的分支名称
  pull_request:
    branches:
      - main  # 在 PR 时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为运行环境

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 3. 运行 Bash 命令编译项目
      - name: Build project
        run: |
          echo "Building project..."
          bash /tools/pack_kernerimage_cmd.sh

      # 4. 上传构建产物（可选）
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: /xiajiaxi/android_kernel_huawei_mate9-mha_harmony2_KernelSU/output  # 替换为你的构建产物路径
